version: '3.7'
services:
  mysql:
    image: "mysql:latest"
    volumes:
      - "mysql_volume:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=sipasdb
    restart: on-failure
    ports:
      - "3307:3306"
    networks:
      - "sipas_network"
networks:
  sipas_network:
volumes:
  mysql_volume: