version: '3.7'
services:
#  mysql:
#    image: "mysql:latest"
#    volumes:
#      - "mysql_volume:/var/lib/mysql"
#    environment:
#      - MYSQL_ROOT_PASSWORD=sipasdb
#    restart: on-failure
#    ports:
#      - "3307:3306"
#    networks:
#      - "sipas_network"
  postgres:
    container_name: "sipas_db"
    image: "postgres:15.5"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"
    restart: on-failure
    networks:
      - "sipas_network"
    environment:
      - POSTGRES_PASSWORD=sipasdb
    ports:
      - "5432:5432"
  redis:
    container_name: "redis_db"
    image: "redis:latest"
    ports:
      - "6380:6379"
    networks:
      - "sipas_network"
  sipas:
    container_name: "sipas_app"
    build: .
    depends_on:
      - "postgres"
      - "redis"
    networks:
      - "sipas_network"
    ports:
      - "8081:8080"
    restart: "on-failure"
networks:
  sipas_network:
volumes:
  mysql_volume:
  postgres_volume: